apiVersion: apps/v1
kind: Deployment
metadata: {name: simubot-api, namespace: simubot}
spec:
  replicas: 1
  selector: {matchLabels: {app: simubot-api}}
  template:
    metadata: {labels: {app: simubot-api}}
    spec:
      containers:
        - name: api
          image: simubot/api:latest
          imagePullPolicy: IfNotPresent
          env:
            - {name: RABBITMQ_URL, value: amqp://guest:guest@rabbitmq.simubot.svc.cluster.local:5672/}
          ports: [{containerPort: 8000}]
---
apiVersion: v1
kind: Service
metadata: {name: simubot-api, namespace: simubot}
spec:
  selector: {app: simubot-api}
  ports:
    - port: 8000
      targetPort: 8000
      name: http
